Master:
  AdminUser: user
  AdminPassword: user
  Jobs:
    coypu_llvm: |-
      <?xml version='1.1' encoding='UTF-8'?>
      <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject plugin="workflow-multibranch@2.20">
       <actions/>
       <description></description>
       <properties>
      <org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty plugin="kubernetes@1.14.0">
      <permittedClouds/>
      </org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty>
      <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.3.4.1">
      <dockerLabel></dockerLabel>
      <registry plugin="docker-commons@1.13"/>
      </org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig>
      </properties>
      <folderViews class="jenkins.branch.MultiBranchProjectViewHolder" plugin="branch-api@2.1.2">  
      <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
      </folderViews>
      <healthMetrics>
       <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@6.7">
        <nonRecursive>false</nonRecursive>
       </com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric>
      </healthMetrics>
      <icon class="jenkins.branch.MetadataActionFolderIcon" plugin="branch-api@2.1.2">
        <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
      </icon>
      <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@6.7">
       <pruneDeadBranches>true</pruneDeadBranches>
       <daysToKeep>-1</daysToKeep>
       <numToKeep>-1</numToKeep>
      </orphanedItemStrategy>
      <triggers/>
       <disabled>false</disabled>
       <sources class="jenkins.branch.MultiBranchProject$BranchSourceList" plugin="branch-api@2.1.2">
        <data>
          <jenkins.branch.BranchSource>
           <source class="jenkins.plugins.git.GitSCMSource" plugin="git@3.9.1">
            <id>d6c2bfd3-7288-4ccb-8132-3ef2a1a3bbae</id>
            <remote>https://github.com/aaronwald/vms</remote>
            <credentialsId></credentialsId>
            <traits>
             <jenkins.plugins.git.traits.BranchDiscoveryTrait/>
            </traits>
           </source>
         <strategy class="jenkins.branch.DefaultBranchPropertyStrategy">
         <properties class="empty-list"/>
         </strategy>
        </jenkins.branch.BranchSource>
        </data>
        <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
       </sources>
       <factory class="org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory">
        <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
        <scriptPath>Jenkinsfile</scriptPath>
       </factory>
      </org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject>
  InstallPlugins:
   - kubernetes:1.14.0
   - workflow-job:2.31
   - workflow-aggregator:2.6
   - credentials-binding:1.17
   - git:3.9.1
   - docker-build-step:2.2
   - google-container-registry-auth:0.3
   - google-oauth-plugin:0.6
Agent:
  Image: adriagalin/jenkins-jnlp-slave
  ImageTag: 1.4
  CustomJenkinsLabels:
    - coypu_llvm
  AlwaysPullImage: true
  resources:
    requests:
      cpu: "500m"
      memory: "2048Mi"
    limits:
      cpu: "500m"
      memory: "2048Mi"
  volumes:
    - type: HostPath
      volumeName: docker-sock
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
