
- hosts: all
  gather_facts: yes
     
  tasks:
    - name: Create a network
      docker_network:
        name: coypu_net

    - name: Zookeeper
      docker_container:
        name: zookeeper
        hostname: coypu-zookeeper
        image: jplock/zookeeper
        ports:
          - "2181:2181"
        networks:
          - name: coypu_net
        purge_networks: yes
        detach: yes
        auto_remove: yes
        
    - name: Kafka
      docker_container:
        name: kafka
        hostname: coypu-kafka
        image: ches/kafka
        networks:
          - name: coypu_net
        purge_networks: yes
        detach: yes
        auto_remove: yes
        ports:
          - "7203:7203"
          - "9092:9092"
        env:
          ZOOKEEPER_IP: zookeeper

    - name: Create kafka topic
      docker_container:
        name: kafka-topic
        image: ches/kafka
        networks:
          - name: coypu_net
        purge_networks: yes
        detach: yes
        auto_remove: yes
        command: kafka-topics.sh --create --topic trades --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181
          
    - name: Postgres
      docker_container:
        name: postgres
        hostname: coypu-postgres
        image: postgres:latest
        detach: yes
        auto_remove: yes
        networks:
          - name: coypu_net
        purge_networks: yes
        ports:
          - "5432:5432"
        volumes:
          - "{{ansible_env.HOME}}/docker/volumes/postgres:/var/lib/postgresql/data"
        env:
          POSTGRES_PASSWORD: docker

    - name: Postgres create database
      docker_container:
        name: postgres-db
        image: postgres:latest
        detach: yes
        auto_remove: yes
        networks:
          - name: coypu_net
        purge_networks: yes
        command: PGPASSWORD=docker psql -hpostgres -U postgres -c 'CREATE DATABASE trades'

    - name: Postgres create last_trade table
      docker_container:
        name: postgres-db
        image: postgres:latest
        detach: yes
        auto_remove: yes
        networks:
          - name: coypu_net
        purge_networks: yes
        command: PGPASSWORD=docker psql -hpostgres -U postgres trades -c 'CREATE TABLE last_trade (trade_id varchar(32) not null primary key, product varchar(8) not null, last_px float not null, last_size float not null)'

        
    - name: Coypu server
      docker_container:
        name: coypu_server
        image: coypu:latest
        detach: yes
        auto_remove: yes
        dns_servers:
          - 8.8.8.8
        networks:
          - name: coypu_net
        purge_networks: yes
        auto_remove: yes

    - name: Coypu load
      docker_container:
        name: coypu_load
        image: coypu_kafka:latest
        detach: yes
        auto_remove: yes
        networks:
          - name: coypu_net
        purge_networks: yes
        auto_remove: yes

