- hosts: all
  become: true
  become_user: root
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
    bits_dir: "/tmp/bits"
    bcc_git_url: https://github.com/iovisor/bcc.git
    bcc_version: v0.7.0
    bpf_git_url: https://github.com/iovisor/bpftrace
    bpf_version: master

  tasks:
    - name: Clone bcc
      git:
        repo: "{{ bcc_git_url }}"
        dest: "{{ bits_dir }}/bcc"
        version: "{{ bcc_version }}"

    - name: Make bcc build
      file:
        path: "{{ bits_dir }}/bcc/build"
        state: directory
        mode: 0755

    - name: bcc cmake
      command: /usr/local/bin/cmake "{{ bits_dir }}/bcc" -DCMAKE_INSTALL_PREFIX=/usr
      args:
        chdir: "{{ bits_dir }}/bcc/build"

    - name: bcc build
      command: make -j 4
      args:
        chdir: "{{ bits_dir }}/bcc/build"

    - name: bcc install
      command: make install
      args:
        chdir: "{{ bits_dir }}/bcc/build"
      
    - name: Clone bpf
      git:
        repo: "{{ bpf_git_url }}"
        dest: "{{ bits_dir }}/bpf"
        version: "{{ bpf_version }}"

    - name: Make bpf build
      file:
        path: "{{ bits_dir }}/bpf/build"
        state: directory
        mode: 0755

    - name: bpf cmake centos
      command: scl enable devtoolset-7 '/usr/local/bin/cmake "{{ bits_dir }}/bpf" -DCMAKE_BUILD_TYPE=DEBUG ..'
      args:
        chdir: "{{ bits_dir }}/bpf/build"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: bpf cmake ubuntu
      command: '/usr/local/bin/cmake "{{ bits_dir }}/bpf" -DCMAKE_BUILD_TYPE=DEBUG ..'
      args:
        chdir: "{{ bits_dir }}/bpf/build"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: bpf build centos
      command: scl enable devtoolset-7 'make -j 4'
      args:
        chdir: "{{ bits_dir }}/bpf/build"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: bpf build ubuntu
      command: 'make -j 4'
      args:
        chdir: "{{ bits_dir }}/bpf/build"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      
    - name: bpf install centos
      command: scl enable devtoolset-7 'make install'
      args:
        chdir: "{{ bits_dir }}/bpf/build"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: bpf install ubuntu
      command: 'make install'
      args:
        chdir: "{{ bits_dir }}/bpf/build"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'