
- hosts: all
  become: true
  become_user: root
  gather_facts: no
  vars:
     ansible_python_interpreter: /usr/bin/python2.7
     ansible_distribution_major_version: 7
     cmake_src_dir: /opt/cmake
     cmake_build_dir: /opt/cmake-build
     git_version: 2.9.5
     cmake_version: 3.12.1
     spdlog_version: v1.1.0
     json_version: v3.3.0
     rapidjson_git_url: https://github.com/Tencent/rapidjson.git
     rapidjson_version: v1.1.0
     rapidjson_dir: "/opt/rapidjson"
     nghttp2_git_url: https://github.com/nghttp2/nghttp2.git
     nghttp2_version: v1.36.0

  tasks:
    - name: Download git
      get_url:
        url: "https://mirrors.edge.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz"
        dest: /opt/

    - name: Untar git
      unarchive:
        src: "/opt/git-{{ git_version }}.tar.gz"
        remote_src: yes
        dest: "/opt"

    - name: Configure git
      command: make configure
      args:
        chdir: "/opt/git-{{ git_version }}/"

    - name: Configure git 2
      command: ./configure --prefix=/usr
      args:
        chdir: "/opt/git-{{ git_version }}/"

    - name: Make git
      command: make all
      args:
        chdir: "/opt/git-{{ git_version }}/"

    - name: Git install
      command: make install
      args:
        chdir: "/opt/git-{{ git_version }}/"
        
    - name: Download cmake
      get_url:
        url: "https://cmake.org/files/v3.12/cmake-{{ cmake_version }}.tar.gz"
        dest: /opt/
        
    - name: Untar cmake
      unarchive:
        src: "/opt/cmake-{{ cmake_version }}.tar.gz"
        remote_src: yes
        dest: "/opt"

    - name: Cmake bootstrap
      command: ./bootstrap
      args:
        chdir: "/opt/cmake-{{ cmake_version }}/"

    - name: Cmake Build
      command: make -j 4
      args:
        chdir: "/opt/cmake-{{ cmake_version }}/"
    
    - name: cmake install
      command: make install
      args:
        chdir: "/opt/cmake-{{ cmake_version }}/"
        
        
    - name: Clone cmake modules
      git:
        repo: https://github.com/rpavlik/cmake-modules.git
        dest: /opt/cmake-modules

    - name: Clone spdlog
      git:
        repo: https://github.com/gabime/spdlog.git
        dest: /opt/spdlog
        version: "{{ spdlog_version }}"

    - name: Make spdlog build dir
      file:
        path: "/opt/spdlog/build"
        state: directory
        mode: 0755

    - name: spdlog Build
      command: /usr/local/bin/cmake /opt/spdlog
      args:
        chdir: "/opt/spdlog/build"

    - name: spdlog Build
      command: make -j 4
      args:
        chdir: "/opt/spdlog/build"
    
    - name: spdlog install
      command: make install
      args:
        chdir: "/opt/spdlog/build"

    - name: Clone json
      git:
        repo: https://github.com/nlohmann/json.git
        dest: /opt/json
        version: "{{ json_version }}"

    - name: Make json build dir
      file:
        path: "/opt/json/build"
        state: directory
        mode: 0755

    - name: json Build
      command: /usr/local/bin/cmake /opt/json
      args:
        chdir: "/opt/json/build"

    - name: json Build
      command: make -j 4
      args:
        chdir: "/opt/json/build"

    - name: json install
      command: make install
      args:
        chdir: "/opt/json/build"
        
    - name: Clone rapidjson
      git:
        repo: "{{ rapidjson_git_url }}"
        dest: "{{ rapidjson_dir }}"
        version: "{{ rapidjson_version }}"

    - name: Clean nghttp2
      file:
        state: absent
        path: "/opt/nghttp2/"
        
    - name: Clone nghttp2
      git:
        repo: "{{ nghttp2_git_url }}"
        dest: /opt/nghttp2
        version: "{{ nghttp2_version }}"

    - name: Configure nghttp2 - git submodule
      command: git submodule update --init
      args:
        chdir: "/opt/nghttp2"

    - name: Configure nghttp2 - autoreconfg
      command: autoreconf -i
      args:
        chdir: "/opt/nghttp2"

    - name: Configure nghttp2 - automake
      command: automake
      args:
        chdir: "/opt/nghttp2"

    - name: Configure nghttp2 - autoconf
      command: autoconf 
      args:
        chdir: "/opt/nghttp2"

    - name: Configure nghttp2 - configure
      command: ./configure
      args:
        chdir: "/opt/nghttp2"

    - name: Build nghttp2
      command: make
      args:
        chdir: "/opt/nghttp2"
      
    - name: Install nghttp2
      command: make install
      args:
        chdir: "/opt/nghttp2"

