
- hosts: all
  become: true
  become_user: root
  gather_facts: yes
  vars:
     ansible_python_interpreter: /usr/bin/python2.7
     
  tasks:
    - name: Remove docker.io
      apt:
        state: absent
        name: "{{ packages }}"
      vars:
        packages:
          - docker
          - docker-engine
          - docker.io

    - name: Add an Apt signing key, will not download if present
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Kube repo
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        
    - name: Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Google cloud sdk repo
      apt_repository:
        repo: deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main
        state: present

    - name: Apt update
      apt:
        update_cache: yes

    - name: Install docker-ce
      apt:
        state: present
        name: docker-ce

    - name: Instal google-cloud-sdk
      apt:
        state: present
        name: google-cloud-sdk
        
    - name: Install kubectl
      apt:
        state: present
        name: kubectl

    - name: Install minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: 0777

    - name: Install kvm2 driver
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2
        dest: /usr/local/bin/
        mode: 0777
        
#    - name: Usermod docker
#      command: usermod -aG docker ${USER}

