
- hosts: all
  become: true
  become_user: root
  gather_facts: no
  vars:
     ansible_python_interpreter: /usr/bin/python2.7
     ansible_distribution_major_version: 7
     llvm_src_dir: /opt/llvm
     clang_release: release_60
     clang_build_dir: /opt/clang-build
     clang_build_type: Release
     install_prefix: /usr

  tasks:
    - name: Clone lvvm
      git: 
        repo: 'https://github.com/llvm-mirror/llvm.git'
        dest: "{{ llvm_src_dir }}"
        version: "{{ clang_release }}"
        
    - name: Clone clang     
      git:
        repo: 'https://github.com/llvm-mirror/clang.git'
        dest: "{{ llvm_src_dir }}/tools/clang"
        version: "{{ clang_release }}"
        
    - name: Clone clang tools extra
      git:
        repo: 'https://github.com/llvm-mirror/clang-tools-extra.git'
        dest: "{{ llvm_src_dir }}/tools/clang/tools/extra"
        version: "{{ clang_release }}"
        
    - name: Clone compiler-rt
      git:
        repo: 'https://github.com/llvm-mirror/compiler-rt.git'
        dest: "{{ llvm_src_dir }}/projects/compiler-rt"
        version: "{{ clang_release }}"

    - name: Clone libcxx
      git:
        repo: 'https://github.com/llvm-mirror/libcxx.git'
        dest: "{{ llvm_src_dir }}/projects/libcxx"
        version: "{{ clang_release }}"

    - name: Clone libcxxabi
      git:
        repo: 'https://github.com/llvm-mirror/libcxxabi.git'
        dest: "{{ llvm_src_dir }}/projects/libcxxabi"
        version: "{{ clang_release }}"
        
    - name: Make clang build dir
      file:
        path: "{{ clang_build_dir }}"
        state: directory
        mode: 0755

    # -DLLVM_USE_LINKER=gold
    - name: llvm CMake
      command: /usr/local/bin/cmake -DCMAKE_BUILD_TYPE="{{ clang_build_type }}" -G "Unix Makefiles" "{{ llvm_src_dir }}" 
      args:
        chdir: "{{ clang_build_dir }}"

    - name: llvm Build
      command: make -j 4
      args:
        chdir: "{{ clang_build_dir }}"

    - name: llvm Build cxx
      command: make -j 4 cxx
      args:
        chdir: "{{ clang_build_dir }}"
    
    - name: llvm install
      command: make install
      args:
        chdir: "{{ clang_build_dir }}"

    - name: llvm install - libcxx
      command: make install
      args:
        chdir: "{{ clang_build_dir }}/projects/libcxx"
        
    - name: llvm install - libcxxabi
      command: make install
      args:
        chdir: "{{ clang_build_dir }}/projects/libcxxabi"
