
- hosts: all
  become: true
  become_user: root
  gather_facts: no
  vars:
     ansible_python_interpreter: /usr/bin/python2.7
     
  tasks:
    - name: Aptitude
      apt:
        name: aptitude 
        state: latest
    
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - build-essential
          - libtool
          - asciidoc 
          - tmux
          - libkmod-dev
          - pkg-config-i686-linux-gnu
          - libudev-dev
          - libudev1
          - uuid
          - uuid-dev
          - libjson-c-dev
          - nvme-cli
          - libunwind-dev
          - emacs-goodies-el
          - vagrant
          - packer
          - ansible
          - python-dev
          - qemu-kvm
          - libvirt-bin
          - ubuntu-vm-builder
          - bridge-utils
          - virtualenv
          - yaml-mode
          - autoconf
          - autoconf-doc
          - zlib1g-dev
          - zsh
          - zsh-doc
          - libcurl4-openssl-dev
          - bison
          - bison-doc
          - flex
          - libelf-dev
          - iperf3
          - netperf
          - arping
          - libyaml-dev
          - libssl-doc
          - libssl-dev
          - libnuma-dev
          - libfl-dev
          - linux-tools-common
          - linux-tools-generic
          - msr-tools
          - iftop
          - cpufrequtils
          - gdb
          - gdb-doc
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Remove docker.io
      apt:
        state: absent
        name: "{{ packages }}"
      vars:
        packages:
          - docker
          - docker-engine
          - docker.io

    - name: Add an Apt signing key, will not download if present
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Apt update
      apt:
        update_cache: yes

    - name: Install docker-ce
      apt:
        state: present
        name: docker-ce

#    - name: Usermod docker
#      command: usermod -aG docker ${USER}
